title: OBX To Do
remote_theme: pages-themes/minimal@v0.2.0 # A clean starting point
plugins:
  - jekyll-remote-theme

# This tells Jekyll to turn each post in the gallery folder into its own page
collections:
  gallery:
    output: true
    permalink: /gallery/:path/
