name: Daily Build
on:
  schedule:
    - cron: '52 12 * * *' # Runs at 12:55 PM UTC (approx. 8:55 AM EDT)
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub Pages rebuild
        run: |
          curl -X POST https://api.github.com/repos/${{ github.repository }}/pages/builds \
          -H "Authorization: token ${{ secrets.SYNC_TOKEN }}"
